export enum ORDER_STATUS {
  PENDING = "PENDING",
  ORDER_ACCEPTED = "ORDER_ACCEPTED",
  ORDER_FINALIZED = "ORDER_FINALIZED",
  ITEM_PAID = "ITEM_PAID",
  ITEM_BOUGHT = "ITEM_BOUGHT",
  EN_ROUTE = "EN_ROUTE",
  DELIVERED = "DELIVERED",
  FUNDS_TRANSFERRED = "FUNDS_TRANSFERRED",
}
